### ISSUE TITLE
java.lang.Exception | Something went wrong, please contact our support

### ISSUE THREAD

**Issue by LinX64** [HabitatMap/AircastingAndroid#381]
I've been facing this problem while I am creating a new session with the Microphone. This may be related to most of the issues that we were facing during the creation of a session. 

Logcat:

```
2022-03-11 01:52:27.883 5458-5458/pl.llp.aircasting W/System.err: java.lang.Exception
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at pl.llp.aircasting.networking.services.MobileSessionUploadService$upload$1.onResponse(MobileSessionUploadService.kt:26)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at android.os.Looper.loop(Looper.java:288)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7902)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
2022-03-11 01:52:27.884 5458-5458/pl.llp.aircasting E/ErrorHandler: Something went wrong, please contact our support.
```

There is also another problem that I just noticed: 

`400 Bad Request http://**hided*****/api/sessions (247ms)`

**Comment by LinX64** [comment]
This error is still happening after reopening the application.
