### ISSUE TITLE
Resource ID #0x7f070016 type #0x3 is not valid

### ISSUE THREAD

**Issue by LinX64** [HabitatMap/AircastingAndroid#391]
This error occurred while I was creating a `Mobile - Microphone session`. It may be related to Google maps and styles, not sure.

```
2022-03-24 01:12:50.063 6147-6147/pl.llp.aircasting E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pl.llp.aircasting, PID: 6147
    android.content.res.Resources$NotFoundException: Resource ID #0x7f070016 type #0x3 is not valid
        at android.content.res.Resources.getDimensionPixelSize(Resources.java:836)
        at com.google.maps.api.android.lib6.impl.ax.d(:com.google.android.gms.dynamite_mapsdynamite@220412104@22.04.12 (190800-0):5)
        at com.google.maps.api.android.lib6.impl.fh.<init>(:com.google.android.gms.dynamite_mapsdynamite@220412104@22.04.12 (190800-0):6)
        at com.google.maps.api.android.lib6.impl.bo.az(:com.google.android.gms.dynamite_mapsdynamite@220412104@22.04.12 (190800-0):16)
        at com.google.maps.api.android.lib6.impl.cr.o(:com.google.android.gms.dynamite_mapsdynamite@220412104@22.04.12 (190800-0):2)
        at com.google.android.gms.maps.internal.o.aX(:com.google.android.gms.dynamite_mapsdynamite@220412104@22.04.12 (190800-0):19)
        at dy.onTransact(:com.google.android.gms.dynamite_mapsdynamite@220412104@22.04.12 (190800-0):4)
        at android.os.Binder.transact(Binder.java:1164)
        at com.google.android.gms.internal.maps.zza.zzH(com.google.android.gms:play-services-maps@@18.0.0:2)
        at com.google.android.gms.maps.internal.zzk.onCreateView(com.google.android.gms:play-services-maps@@18.0.0:5)
        at com.google.android.gms.maps.zzau.onCreateView(com.google.android.gms:play-services-maps@@18.0.0:7)
        at com.google.android.gms.dynamic.zad.zab(com.google.android.gms:play-services-base@@18.0.1:2)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaf(com.google.android.gms:play-services-base@@18.0.1:1)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreateView(com.google.android.gms:play-services-base@@18.0.1:2)
        at com.google.android.gms.maps.SupportMapFragment.onCreateView(com.google.android.gms:play-services-maps@@18.0.0:1)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3023)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1396)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2911)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2825)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3048)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1780)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:510)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7850)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by LinX64** [comment]
Fix: https://github.com/HabitatMap/AircastingAndroid/pull/406
