### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by LinX64** [HabitatMap/AircastingAndroid#403]
This crash occurs while I am logging in and I am waiting in the following tab. I think the problem is related to `session.endTime!!`. Working on it.

```
2022-03-30 11:11:34.877 28898-28947/pl.llp.aircasting E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: pl.llp.aircasting, PID: 28898
    java.lang.NullPointerException
        at pl.llp.aircasting.networking.params.SessionParams.<init>(SessionParams.kt:21)
        at pl.llp.aircasting.networking.services.MobileSessionUploadService.upload(MobileSessionUploadService.kt:16)
        at pl.llp.aircasting.networking.services.SessionsSyncService.upload(SessionsSyncService.kt:156)
        at pl.llp.aircasting.networking.services.SessionsSyncService.access$upload(SessionsSyncService.kt:26)
        at pl.llp.aircasting.networking.services.SessionsSyncService$sync$1$1$onResponse$1$1.invoke(SessionsSyncService.kt:113)
        at pl.llp.aircasting.networking.services.SessionsSyncService$sync$1$1$onResponse$1$1.invoke(SessionsSyncService.kt:110)
        at pl.llp.aircasting.database.DatabaseProvider$Companion$runQuery$1.invokeSuspend(DatabaseProvider.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by LinX64** [comment]
Fix: https://github.com/HabitatMap/AircastingAndroid/pull/405
